// Code generated by tdl. DO NOT EDIT.

package model

// Cluster-wide utilization, absent when node-exporter has no data.
type Cluster struct {
	CPUPct *float64 `json:"cpuPct"`
	MemPct *float64 `json:"memPct"`
}
