// Code generated by tdl. DO NOT EDIT.

package model

import (
	"errors"
	"fmt"
)

// The last 15 minutes of samples: cpu and mem in percent, disk and net in bytes/sec.
type NodeSeries struct {
	CPU  []Point `json:"cpu"`
	Mem  []Point `json:"mem"`
	Disk []Point `json:"disk"`
	Net  []Point `json:"net"`
}

// Validate reports every constraint NodeSeries breaks, joined, or nil.
func (n NodeSeries) Validate() error {
	return errors.Join(n.validate("NodeSeries", nil)...)
}

func (n NodeSeries) validate(path string, errs []error) []error {
	for idx, elem := range n.CPU {
		errs = elem.validate(fmt.Sprintf("%s.cpu[%d]", path, idx), errs)
	}
	for idx, elem := range n.Mem {
		errs = elem.validate(fmt.Sprintf("%s.mem[%d]", path, idx), errs)
	}
	for idx, elem := range n.Disk {
		errs = elem.validate(fmt.Sprintf("%s.disk[%d]", path, idx), errs)
	}
	for idx, elem := range n.Net {
		errs = elem.validate(fmt.Sprintf("%s.net[%d]", path, idx), errs)
	}
	return errs
}
