// Code generated by tdl. DO NOT EDIT.

package model

import "errors"

type Node struct {
	Name      string     `json:"name"`
	Role      string     `json:"role"`
	Arch      string     `json:"arch,omitempty"`
	Health    Health     `json:"health"`
	Reasons   []string   `json:"reasons"`
	Ready     bool       `json:"ready"`
	Cordoned  bool       `json:"cordoned"`
	Exporter  bool       `json:"exporter"`
	RootFSPct *float64   `json:"rootFsPct"`
	Series    NodeSeries `json:"series"`
}

// Validate reports every constraint Node breaks, joined, or nil.
func (n Node) Validate() error {
	return errors.Join(n.validate("Node", nil)...)
}

func (n Node) validate(path string, errs []error) []error {
	errs = n.Series.validate(path+".series", errs)
	return errs
}
