// Code generated by tdl. DO NOT EDIT.

package model

import (
	"errors"
	"fmt"
)

// A [unix seconds, value] sample.
type Point []float64

// Validate reports every constraint Point breaks, joined, or nil.
func (p Point) Validate() error {
	return errors.Join(p.validate("Point", nil)...)
}

func (p Point) validate(path string, errs []error) []error {
	if count := len(p); count < 2 || count > 2 {
		errs = append(errs, fmt.Errorf("%s: length(2..2): got %d", path, count))
	}
	return errs
}
