// Code generated by tdl. DO NOT EDIT.

package model

import (
	"errors"
	"fmt"
	"time"
)

// The response body of GET /api/nodes.
type Snapshot struct {
	Updated time.Time `json:"updated"`
	Cluster Cluster   `json:"cluster"`
	Nodes   []Node    `json:"nodes"`
}

// Validate reports every constraint Snapshot breaks, joined, or nil.
func (s Snapshot) Validate() error {
	return errors.Join(s.validate("Snapshot", nil)...)
}

func (s Snapshot) validate(path string, errs []error) []error {
	for idx, elem := range s.Nodes {
		errs = elem.validate(fmt.Sprintf("%s.nodes[%d]", path, idx), errs)
	}
	return errs
}
