apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thecluster.fullname" . }}
  labels:
    {{- include "thecluster.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "thecluster.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "thecluster.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: thecluster
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.service.targetPort | quote }}
            - name: STATIC_DIR
              value: /wwwroot
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
